### ISSUE TITLE
¿Es valida esta solución? 

### ISSUE THREAD

**Issue by abilbaotm** [programGrupo7/grupo7#12]
https://github.com/programGrupo7/grupo7/commit/45a575a6e8bb95101f65bd066be89b0a8f912e65#diff-5dc7fffed86a5b9c72f1b2ab9bdd28c3R26

**Comment by Sheila29** [comment]
No ha habido manera de hacerle ninguna pregunta hoy a Ion.
Voy a hacer el resto de clases como esto y si está mal las cambio otra vez y ya está.

**Comment by Sheila29** [comment]
Tenemos que pasarle un objeto de la clase como parámetro no todos los campos.
