### ISSUE TITLE
Escribir el blog de esta seman

### ISSUE THREAD

**Issue by Sheila29** [programGrupo7/grupo7#13]

**Comment by abilbaotm** [comment]
Cosas que hemos hecho:
- Travis
- Crear UI
- Crear conexión BBDD
- Manejo basico de información con persistencia en BBDD. ver https://github.com/programGrupo7/grupo7/issues/13#issuecomment-292014838

**Comment by abilbaotm** [comment]
- Manejo basico de información con persistencia en BBDD.
     - Crear centros 1ef4450d90663ce3fb7882039587dba157ca4eea
     - Listar centros en una tabla d2165b2ec9eb27e4d11bcc94d60c1eebf9a8621a

**Comment by Sheila29** [comment]
Hecho! si quieres leerlo o cambiar algo me dices....
